/**
 * File storage with two interchangeable drivers.
 *
 *   local (default) — writes under STORAGE_LOCAL_DIR. Zero setup, works
 *                     offline, and is the right choice for development and for
 *                     single-instance deployments with a persistent volume.
 *   s3              — any S3-compatible service (AWS S3, Cloudflare R2, MinIO,
 *                     Backblaze B2). Downloads are served by redirecting to a
 *                     short-lived presigned URL so bytes never transit this
 *                     process.
 *
 * Both drivers obey the same rules:
 *  • Object keys are generated by the server (`putObject`), never taken from
 *    user input, so path traversal is impossible by construction.
 *  • Anything read back goes through `assertSafeKey`, which rejects `..`,
 *    absolute paths, control characters, and backslashes even for keys that did
 *    not come from the generator — defence in depth, since old rows and manual
 *    database edits exist.
 *  • Uploads are size-checked and content-type-checked BEFORE bytes are
 *    written, using the configured limits.
 *
 * The authorization decision (may this user read/delete this object?) lives in
 * the HTTP layer, next to the database row. Storage only moves bytes.
 */
import { mkdir, readFile, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { BadRequestError, NotFoundError, PayloadTooLargeError } from "@shared/errors";
import { ENV } from "../env";
import { logger } from "../logger";
import { presignUrl, type SigV4Credentials } from "./sigv4";

export type StorageDriverName = "local" | "s3";

export type StoredObject = {
  key: string;
  /** Bytes actually written. */
  size: number;
  contentType: string;
};

export type ObjectBody = {
  data: Buffer;
  contentType: string;
  size: number;
};

export type StorageDriver = {
  name: StorageDriverName;
  /** Writes bytes and returns the generated key. */
  putObject(
    data: Buffer,
    options: { contentType: string; prefix?: string; originalName?: string }
  ): Promise<StoredObject>;
  /** Reads bytes back. Returns null when the object does not exist. */
  getObject(key: string): Promise<ObjectBody | null>;
  deleteObject(key: string): Promise<void>;
  /**
   * URL a browser can fetch directly for `ttlSeconds`, or null when the driver
   * has no notion of a presigned URL (local disk).
   */
  presignGet(key: string, ttlSeconds: number): string | null;
  /**
   * URL a browser can PUT to. Same caveat as `presignGet`: within the TTL,
   * whoever holds the URL can write any bytes to that exact key, so the TTL is
   * short and the server-side upload path is the default.
   */
  presignPut(key: string, contentType: string, ttlSeconds: number): string | null;
};

// ─────────────────────────────────────────────────────────────────────────────
// Key handling
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Keys are `prefix/yyyy/mm/uuid[safe-ext]`. The UUID makes guessing
 * impractical, and the dated prefix keeps listings usable as the bucket grows.
 */
export function buildObjectKey(prefix = "uploads", originalName?: string): string {
  const now = new Date();
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  // A prefix is caller-supplied convenience, not a trust boundary: strip
  // everything that is not a path-safe character, then drop leading/trailing
  // separators so "../../etc" can never become an absolute or parent path.
  const safePrefix =
    prefix
      .toLowerCase()
      .replace(/[^a-z0-9/_-]/g, "")
      .replace(/\/{2,}/g, "/")
      .replace(/^\/+|\/+$/g, "") || "uploads";
  const safeExtension = originalName ? extensionOf(originalName) : "";
  return `${safePrefix}/${year}/${month}/${randomUUID()}${safeExtension}`;
}

/** Extension only, whitelisted characters, max 10 chars — never a path. */
function extensionOf(name: string): string {
  const match = /\.([A-Za-z0-9]{1,10})$/.exec(name);
  return match ? `.${match[1]!.toLowerCase()}` : "";
}

/**
 * Rejects anything that is not a plain relative object key. Called on every key
 * that comes back from the database or a URL, so a tampered row cannot be used
 * to read outside the storage root.
 */
export function assertSafeKey(key: string): void {
  if (!key || key.length > 512) throw BadRequestError("Invalid file key");
  if (key.startsWith("/") || key.endsWith("/")) throw BadRequestError("Invalid file key");
  if (key.includes("..") || key.includes("\\") || key.includes("\0")) {
    throw BadRequestError("Invalid file key");
  }
  // eslint-disable-next-line no-control-regex
  if (/[\u0000-\u001f\u007f]/.test(key)) throw BadRequestError("Invalid file key");
  if (!/^[A-Za-z0-9/._-]+$/.test(key)) throw BadRequestError("Invalid file key");
}

/**
 * Content-type allow-list policy.
 *
 * HTML and SVG are deliberately excluded from inline serving: both can execute
 * script in this origin. If your product genuinely needs to accept them, accept
 * them but serve with `Content-Disposition: attachment` (which is what the
 * download route does for SVG) and never from the app's own origin.
 */
const ALLOWED_CONTENT_TYPES = new Set([
  "image/png",
  "image/jpeg",
  "image/webp",
  "image/gif",
  "image/avif",
  "application/pdf",
  "text/plain",
  "text/csv",
  "text/markdown",
  "application/json",
  "application/zip",
  "application/octet-stream",
  "audio/mpeg",
  "audio/wav",
  "video/mp4",
  "video/webm",
]);

export function assertUploadAllowed(contentType: string, size: number): void {
  if (size <= 0) throw BadRequestError("Empty upload");
  if (size > ENV.STORAGE_MAX_UPLOAD_BYTES) {
    throw PayloadTooLargeError(
      `Files must be ${Math.floor(ENV.STORAGE_MAX_UPLOAD_BYTES / (1024 * 1024))} MB or smaller`
    );
  }
  const normalized = contentType.split(";")[0]!.trim().toLowerCase();
  if (!ALLOWED_CONTENT_TYPES.has(normalized)) {
    throw BadRequestError(
      `${contentType || "That file type"} is not accepted. Allowed: ${[...ALLOWED_CONTENT_TYPES].join(", ")}`
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Local driver
// ─────────────────────────────────────────────────────────────────────────────

function resolveLocalPath(key: string): string {
  assertSafeKey(key);
  const root = path.resolve(process.cwd(), ENV.STORAGE_LOCAL_DIR);
  const target = path.resolve(root, key);
  // Belt and braces: after resolution the path must still be inside the root.
  if (target !== root && !target.startsWith(root + path.sep)) {
    throw BadRequestError("Invalid file key");
  }
  return target;
}

function createLocalDriver(): StorageDriver {
  const root = path.resolve(process.cwd(), ENV.STORAGE_LOCAL_DIR);

  return {
    name: "local",

    async putObject(data, options) {
      const key = buildObjectKey(options.prefix, options.originalName);
      const target = resolveLocalPath(key);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, data);
      logger.debug("stored object locally", { key, size: data.byteLength });
      return { key, size: data.byteLength, contentType: options.contentType };
    },

    async getObject(key) {
      const target = resolveLocalPath(key);
      try {
        const info = await stat(target);
        if (!info.isFile()) return null;
        const data = await readFile(target);
        return {
          data,
          size: data.byteLength,
          contentType: contentTypeForExtension(key),
        };
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
        throw error;
      }
    },

    async deleteObject(key) {
      try {
        await unlink(resolveLocalPath(key));
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      }
    },

    presignGet: () => null,
    presignPut: () => null,
  };
}

/** Best-effort type for objects stored without one (the local driver). */
function contentTypeForExtension(key: string): string {
  const extension = path.extname(key).toLowerCase();
  const map: Record<string, string> = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".avif": "image/avif",
    ".svg": "image/svg+xml", // served as an attachment, never inline
    ".pdf": "application/pdf",
    ".txt": "text/plain; charset=utf-8",
    ".csv": "text/csv; charset=utf-8",
    ".md": "text/markdown; charset=utf-8",
    ".json": "application/json",
    ".mp4": "video/mp4",
    ".webm": "video/webm",
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".zip": "application/zip",
  };
  return map[extension] ?? "application/octet-stream";
}

// ─────────────────────────────────────────────────────────────────────────────
// S3 driver
// ─────────────────────────────────────────────────────────────────────────────

function s3Config(): {
  endpoint: string;
  bucket: string;
  region: string;
  credentials: SigV4Credentials;
  forcePathStyle: boolean;
} {
  const missing = (["S3_BUCKET", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY"] as const).filter(
    (name) => !ENV[name]
  );
  if (missing.length > 0) {
    // Reached when the object endpoints are called without configuration — a
    // clear message beats a confusing TypeError deep in the signing code.
    throw new Error(
      `STORAGE_DRIVER=s3 requires ${missing.join(", ")}. Set them or switch to STORAGE_DRIVER=local.`
    );
  }

  return {
    endpoint: ENV.S3_ENDPOINT ?? `https://s3.${ENV.S3_REGION}.amazonaws.com`,
    bucket: ENV.S3_BUCKET!,
    region: ENV.S3_REGION,
    credentials: {
      accessKeyId: ENV.S3_ACCESS_KEY_ID!,
      secretAccessKey: ENV.S3_SECRET_ACCESS_KEY!,
    },
    forcePathStyle: ENV.S3_FORCE_PATH_STYLE,
  };
}

function objectUrl(key: string): string {
  assertSafeKey(key);
  const config = s3Config();
  const endpoint = new URL(config.endpoint);
  const encodedKey = key.split("/").map(encodeURIComponent).join("/");
  return config.forcePathStyle
    ? `${endpoint.protocol}//${endpoint.host}/${config.bucket}/${encodedKey}`
    : `${endpoint.protocol}//${config.bucket}.${endpoint.host}/${encodedKey}`;
}

function createS3Driver(): StorageDriver {
  return {
    name: "s3",

    async putObject(data, options) {
      const key = buildObjectKey(options.prefix, options.originalName);
      const config = s3Config();
      const url = objectUrl(key);

      // The server signs the same kind of PUT it would hand a browser, then
      // performs it — one signing path, so it cannot work for clients and fail
      // for us (or the reverse).
      const signed = presignUrl({
        method: "PUT",
        endpoint: config.endpoint,
        bucket: config.bucket,
        key,
        region: config.region,
        credentials: config.credentials,
        expiresInSeconds: 300,
        forcePathStyle: config.forcePathStyle,
        extraQuery: { "x-amz-meta-content-type": options.contentType },
      });

      const response = await fetch(signed, {
        method: "PUT",
        headers: { "content-type": options.contentType },
        body: new Uint8Array(data),
      });

      if (!response.ok) {
        const detail = await response.text().catch(() => "");
        logger.error("s3 upload failed", { key, status: response.status, detail: detail.slice(0, 500) });
        throw new Error(`Storage upload failed (${response.status})`);
      }

      logger.debug("stored object in s3", { key, size: data.byteLength, url });
      return { key, size: data.byteLength, contentType: options.contentType };
    },

    async getObject(key) {
      const response = await fetch(objectUrl(key));
      if (response.status === 404) return null;
      if (!response.ok) {
        throw NotFoundError(`Could not read object (${response.status})`);
      }
      const data = Buffer.from(await response.arrayBuffer());
      return {
        data,
        size: data.byteLength,
        contentType: response.headers.get("content-type") ?? contentTypeForExtension(key),
      };
    },

    async deleteObject(key) {
      const config = s3Config();
      const signed = presignUrl({
        method: "DELETE",
        endpoint: config.endpoint,
        bucket: config.bucket,
        key,
        region: config.region,
        credentials: config.credentials,
        expiresInSeconds: 120,
        forcePathStyle: config.forcePathStyle,
      });
      const response = await fetch(signed, { method: "DELETE" });
      // 404 means it is already gone, which is the outcome we wanted.
      if (!response.ok && response.status !== 404) {
        throw new Error(`Storage delete failed (${response.status})`);
      }
    },

    presignGet(key, ttlSeconds) {
      assertSafeKey(key);
      const config = s3Config();
      return presignUrl({
        method: "GET",
        endpoint: config.endpoint,
        bucket: config.bucket,
        key,
        region: config.region,
        credentials: config.credentials,
        expiresInSeconds: ttlSeconds,
        forcePathStyle: config.forcePathStyle,
      });
    },

    presignPut(key, contentType, ttlSeconds) {
      assertSafeKey(key);
      const config = s3Config();
      return presignUrl({
        method: "PUT",
        endpoint: config.endpoint,
        bucket: config.bucket,
        key,
        region: config.region,
        credentials: config.credentials,
        expiresInSeconds: ttlSeconds,
        forcePathStyle: config.forcePathStyle,
        extraQuery: { "x-amz-meta-content-type": contentType },
      });
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────

let cached: StorageDriver | null = null;

export function storage(): StorageDriver {
  if (!cached) {
    cached = ENV.STORAGE_DRIVER === "s3" ? createS3Driver() : createLocalDriver();
    logger.info("storage driver ready", {
      driver: cached.name,
      ...(cached.name === "local" ? { dir: ENV.STORAGE_LOCAL_DIR } : { bucket: ENV.S3_BUCKET }),
    });
  }
  return cached;
}

/** Where the app's own download route serves this object from. */
export function objectDownloadUrl(key: string): string {
  return `/api/files/${key.split("/").map(encodeURIComponent).join("/")}`;
}
