/**
 * Consent-gated analytics loader — the ONLY place third-party scripts are
 * injected.
 *
 * Rules this file enforces:
 *  • Nothing loads before `analytics` consent is true. No "load then disable".
 *  • Revoking consent removes the script tags and clears known cookies.
 *  • No analytics when the driver is unset (the default), so a fresh clone
 *    ships zero third-party code.
 *
 * Supported drivers, both privacy-friendly and cookieless-by-default:
 *   VITE_ANALYTICS_DRIVER=umami|plausible
 *   VITE_ANALYTICS_SRC=https://analytics.example.com/script.js
 *   VITE_ANALYTICS_SITE_ID=...
 *
 * Adding GA4 or a pixel? Do not edit this file to `innerHTML` a remote
 * snippet — add a driver function below so the consent gate cannot be bypassed.
 */
import type { ConsentState } from "@shared/consent";

const SCRIPT_ID = "consent-gated-analytics";

const KNOWN_ANALYTICS_COOKIES = [
  "_ga",
  "_gid",
  "_gat",
  "_gcl_au",
  "_fbp",
  "plausible_ignore",
];

function driver(): string {
  return (import.meta.env.VITE_ANALYTICS_DRIVER as string | undefined) ?? "none";
}

function src(): string {
  return (import.meta.env.VITE_ANALYTICS_SRC as string | undefined) ?? "";
}

function siteId(): string {
  return (import.meta.env.VITE_ANALYTICS_SITE_ID as string | undefined) ?? "";
}

export function isAnalyticsConfigured(): boolean {
  return driver() !== "none" && src().length > 0;
}

function injectScript(): void {
  if (typeof document === "undefined") return;
  if (document.getElementById(SCRIPT_ID)) return;
  if (!isAnalyticsConfigured()) return;

  const script = document.createElement("script");
  script.id = SCRIPT_ID;
  script.defer = true;
  script.src = src();
  script.setAttribute("data-website-id", siteId());
  script.setAttribute("data-domain", window.location.hostname);
  document.head.appendChild(script);
}

function removeScript(): void {
  if (typeof document === "undefined") return;
  document.getElementById(SCRIPT_ID)?.remove();
}

function clearAnalyticsCookies(): void {
  if (typeof document === "undefined") return;
  for (const name of KNOWN_ANALYTICS_COOKIES) {
    document.cookie = `${name}=; Max-Age=0; path=/`;
    document.cookie = `${name}=; Max-Age=0; path=/; domain=.${window.location.hostname}`;
  }
}

/**
 * Idempotent reconciliation. Called on every consent change, so it must be
 * safe to call repeatedly.
 */
export function applyConsentToAnalytics(state: ConsentState): void {
  if (state.analytics) {
    injectScript();
  } else {
    removeScript();
    clearAnalyticsCookies();
  }
}

/**
 * Track an event, but only when consent allows it. Never include personal data
 * (email, name, user id, free-text) in analytics properties — that turns a
 * "statistics" purpose into something users did not consent to.
 */
export function trackEvent(name: string, properties?: Record<string, string | number>): void {
  if (!state_allows()) return;
  const w = window as unknown as {
    umami?: { track: (n: string, p?: Record<string, unknown>) => void };
    plausible?: (n: string, p?: { props?: Record<string, unknown> }) => void;
  };
  try {
    if (driver() === "umami" && w.umami) w.umami.track(name, properties);
    if (driver() === "plausible" && w.plausible) w.plausible(name, { props: properties });
  } catch {
    // Analytics must never break the app.
  }
}

function state_allows(): boolean {
  if (typeof window === "undefined") return false;
  try {
    const raw = window.localStorage.getItem("spawnpoint.consent");
    if (!raw) return false;
    const parsed = JSON.parse(raw) as { state?: { analytics?: boolean } };
    return parsed.state?.analytics === true;
  } catch {
    return false;
  }
}
