import { useState } from "react";
import { toast } from "sonner";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { AiDisclosureNote } from "@/components/AiDisclosureNote";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

/**
 * Example AI feature.
 *
 * Everything an AI feature in this template must do, in one place:
 *  1. never sends a prompt before the user has typed one (no "suggestions" that
 *     silently spend the API budget),
 *  2. renders the Art. 50 disclosure next to the output,
 *  3. keeps the conversation in component state — it is not persisted, so there
 *     is no new personal data to disclose, retain, or delete,
 *  4. surfaces provider failures as a plain message, never a stack trace.
 *
 * Replace the system prompt and the copy; keep the four properties above.
 */
export function AiAssistantCard({ className }: { className?: string }) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [provider, setProvider] = useState<{ provider: string; url: string | null } | null>(null);

  const ask = trpc.system.askAi.useMutation({
    onSuccess: (result) => {
      setMessages((current) => [...current, { role: "assistant", content: result.answer }]);
      setProvider(result.disclosure);
    },
    onError: (error) => {
      toast.error(error.message);
      // Leave the user's message in place so they can retry without retyping.
    },
  });

  const send = (content: string) => {
    const userMessage: Message = { role: "user", content };
    const next: Message[] = [...messages, userMessage].slice(-20);
    setMessages(next);
    ask.mutate({ prompt: content });
  };

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle>AI assistant</CardTitle>
        <CardDescription>
          A working example of a model call: authenticated, rate limited per account, and
          labelled. The conversation stays in this tab.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <AIChatBox
          messages={messages}
          onSendMessage={send}
          isLoading={ask.isPending}
          height={420}
          placeholder="Ask something…"
          emptyStateMessage="Ask a question to try the configured model."
          suggestedPrompts={["Explain what this starter template does in two sentences."]}
        />

        {/* Required by EU AI Act Art. 50: the user must be able to tell that the
            output came from a machine, and know who the provider is. */}
        <AiDisclosureNote variant="block" text="Responses above are generated by a language model." />

        {provider?.url && (
          <p className="text-xs text-muted-foreground">
            Provider: {provider.provider} ·{" "}
            <a
              href={provider.url}
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2"
            >
              their terms
            </a>
          </p>
        )}
      </CardContent>
    </Card>
  );
}
